services:
  ui:
    container_name: ui_wrdip_prod
    build:
      context: ui
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
    command: "npm start"
  
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/data/mysql:/var/lib/mysql
    env_file:
      - .env