services:
  ui:
    container_name: ui_dev
    build:
      context: ./
      dockerfile: ui/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start
    env_file:
      - path: ./.env
        required: true
      
  api:
    container_name: api_dev
    build:
      context: ./
      dockerfile: api/Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./api:/app
    command: 
      sh -c "npm install && npx nodemon server.js"
    env_file:
      - path: ./.env
        required: true

  # mysql:
  #   container_name: db_dev
  #   image: mysql:latest
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   # environment:
  #     # - MYSQL_DATABASE=${DATABASE_NAME}_${DEPLOY_MODE} not needed
  #   env_file:
  #     - path: ./.env
  #       required: true

  db:
    container_name: db_dev
    image: postgres
    restart: always
    volumes:
      #- db-data:/var/lib/postgresql/data
      - ./db/data:/var/lib/postgresql/18/main
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - path: ./.env
        required: true

# volumes:
#   db-data:
#     name: wramp-db-volume