FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    systemd \
    nano \
    curl \
    tmux \
    htop \
    iputils-ping \
    supervisor \
    libpq-dev \
    gcc \    
    python3 \
    python3-pip \
    python3-venv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y init && apt-get clean all

COPY /python-api/requirements.txt /app/requirements.txt

RUN python3 -m venv /app/venv

ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip3 install --no-cache-dir -r /app/requirements.txt

CMD ["/sbin/init"]
