FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    systemd \
    nano \
    curl \
    tmux \
    htop \
    iputils-ping \
    supervisor \
    libpq-dev \
    gcc \
    g++ \
    python3 \
    python3-pip \
    python3-venv \ 
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y init && apt-get clean all

WORKDIR /app

COPY python-api/src/ ./src/

COPY python-api/requirements.txt .

RUN python3 -m venv venv

RUN . venv/bin/activate && pip install --upgrade pip

ENV PATH="/app/venv/bin:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

CMD ["/sbin/init"]

