@baseUrl = http://localhost:4000

################################################### Weather ###################################################

### Create Country
GET {{baseUrl}}/weather/city?cityCode=nt

### Read countries
GET {{baseUrl}}/countries

### Read country by id
GET {{baseUrl}}/countries

### List Users by id
POST {{baseUrl}}/login/users

### Create User
POST {{baseUrl}}/login/createUser
Content-Type: application/json

{"username":"test","password":"test","email":"test@example.com","name":"Test User"}

### test
POST {{baseUrl}}/login/test
Content-Type: application/json

{"test":"hello"}

### devtestemail

GET {{baseUrl}}/dev/sendtestemail

### test
POST {{baseUrl}}/login/

### Weather

GET {{baseUrl}}/weather/

### dev route
GET {{baseUrl}}/dev/
