name: Deploy to Production
on:
  push:
    branches: [ mr/main/working ]

jobs:
  deploy-production:
    runs-on: production
    steps:
    - name: Deploy to Production
      run: sudo -s /scripts/github-deploy-production.sh

